<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->insert([
            ['iso3' =>'AFN' , 'name' => 'Afghani', 'symbol' => '؋' ],
            ['iso3' =>'ALL' , 'name' => 'Lek', 'symbol' => 'Lek' ],
            ['iso3' =>'ANG' , 'name' => 'Netherlands Antillian Guilder', 'symbol' => 'ƒ' ],
            ['iso3' =>'ARS' , 'name' => 'Argentine Peso', 'symbol' => '$' ],
            ['iso3' =>'AUD' , 'name' => 'Australian Dollar', 'symbol' => '$' ],
            ['iso3' =>'AWG' , 'name' => 'Aruban Guilder', 'symbol' => 'ƒ' ],
            ['iso3' =>'AZN' , 'name' => 'Azerbaijanian Manat', 'symbol' => 'ман' ],
            ['iso3' =>'BAM' , 'name' => 'Convertible Marks', 'symbol' => 'KM' ],
            ['iso3' => 'BDT', 'name' => 'Bangladeshi Taka', 'symbol' => '৳'],
            ['iso3' =>'BBD' , 'name' => 'Barbados Dollar', 'symbol' => '$' ],
            ['iso3' =>'BGN' , 'name' => 'Bulgarian Lev', 'symbol' => 'лв' ],
            ['iso3' =>'BMD' , 'name' => 'Bermudian Dollar', 'symbol' => '$' ],
            ['iso3' =>'BND' , 'name' => 'Brunei Dollar', 'symbol' => '$' ],
            ['iso3' =>'BOB' , 'name' => 'BOV Boliviano Mvdol', 'symbol' => '$b' ],
            ['iso3' =>'BRL' , 'name' => 'Brazilian Real', 'symbol' => 'R$' ],
            ['iso3' =>'BSD' , 'name' => 'Bahamian Dollar', 'symbol' => '$' ],
            ['iso3' =>'BWP' , 'name' => 'Pula', 'symbol' => 'P' ],
            ['iso3' =>'BYR' , 'name' => 'Belarussian Ruble', 'symbol' => '₽' ],
            ['iso3' =>'BZD' , 'name' => 'Belize Dollar', 'symbol' => 'BZ$' ],
            ['iso3' =>'CAD' , 'name' => 'Canadian Dollar', 'symbol' => '$' ],
            ['iso3' =>'CHF' , 'name' => 'Swiss Franc', 'symbol' => 'CHF' ],
            ['iso3' =>'CLP' , 'name' => 'CLF Chilean Peso Unidades de fomento', 'symbol' => '$' ],
            ['iso3' =>'CNY' , 'name' => 'Yuan Renminbi', 'symbol' => '¥' ],
            ['iso3' =>'COP' , 'name' => 'COU Colombian Peso Unidad de Valor Real', 'symbol' => '$' ],
            ['iso3' =>'CRC' , 'name' => 'Costa Rican Colon', 'symbol' => '₡' ],
            ['iso3' =>'CUP' , 'name' => 'CUC Cuban Peso Peso Convertible', 'symbol' => '₱' ],
            ['iso3' =>'CZK' , 'name' => 'Czech Koruna', 'symbol' => 'Kč' ],
            ['iso3' =>'DKK' , 'name' => 'Danish Krone', 'symbol' => 'kr' ],
            ['iso3' =>'DOP' , 'name' => 'Dominican Peso', 'symbol' => 'RD$' ],
            ['iso3' =>'EGP' , 'name' => 'Egyptian Pound', 'symbol' => '£' ],
            ['iso3' =>'EUR' , 'name' => 'Euro', 'symbol' => '€' ],
            ['iso3' =>'FJD' , 'name' => 'Fiji Dollar', 'symbol' => '$' ],
            ['iso3' =>'FKP' , 'name' => 'Falkland Islands Pound', 'symbol' => '£' ],
            ['iso3' =>'GBP' , 'name' => 'Pound Sterling', 'symbol' => '£' ],
            ['iso3' =>'GIP' , 'name' => 'Gibraltar Pound', 'symbol' => '£' ],
            ['iso3' =>'GTQ' , 'name' => 'Quetzal', 'symbol' => 'Q' ],
            ['iso3' =>'GYD' , 'name' => 'Guyana Dollar', 'symbol' => '$' ],
            ['iso3' =>'HKD' , 'name' => 'Hong Kong Dollar', 'symbol' => '$' ],
            ['iso3' =>'HNL' , 'name' => 'Lempira', 'symbol' => 'L' ],
            ['iso3' =>'HRK' , 'name' => 'Croatian Kuna', 'symbol' => 'kn' ],
            ['iso3' =>'HUF' , 'name' => 'Forint', 'symbol' => 'Ft' ],
            ['iso3' =>'IDR' , 'name' => 'Rupiah', 'symbol' => 'Rp' ],
            ['iso3' =>'ILS' , 'name' => 'New Israeli Sheqel', 'symbol' => '₪' ],
            ['iso3' =>'IRR' , 'name' => 'Iranian Rial', 'symbol' => '﷼' ],
            ['iso3' =>'ISK' , 'name' => 'Iceland Krona', 'symbol' => 'kr' ],
            ['iso3' =>'JMD' , 'name' => 'Jamaican Dollar', 'symbol' => 'J$' ],
            ['iso3' =>'JPY' , 'name' => 'Yen', 'symbol' => '¥' ],
            ['iso3' =>'KGS' , 'name' => 'Som', 'symbol' => 'лв' ],
            ['iso3' =>'KHR' , 'name' => 'Riel', 'symbol' => '៛' ],
            ['iso3' =>'KPW' , 'name' => 'North Korean Won', 'symbol' => '₩' ],
            ['iso3' =>'KRW' , 'name' => 'Won', 'symbol' => '₩' ],
            ['iso3' =>'KYD' , 'name' => 'Cayman Islands Dollar', 'symbol' => '$' ],
            ['iso3' =>'KZT' , 'name' => 'Tenge', 'symbol' => 'лв' ],
            ['iso3' =>'LAK' , 'name' => 'Kip', 'symbol' => '₭' ],
            ['iso3' =>'LBP' , 'name' => 'Lebanese Pound', 'symbol' => '£' ],
            ['iso3' =>'LKR' , 'name' => 'Sri Lanka Rupee', 'symbol' => '₨' ],
            ['iso3' =>'LRD' , 'name' => 'Liberian Dollar', 'symbol' => '$' ],
            ['iso3' =>'LTL' , 'name' => 'Lithuanian Litas', 'symbol' => 'Lt' ],
            ['iso3' =>'LVL' , 'name' => 'Latvian Lats', 'symbol' => 'Ls' ],
            ['iso3' =>'MKD' , 'name' => 'Denar', 'symbol' => 'ден' ],
            ['iso3' =>'MNT' , 'name' => 'Tugrik', 'symbol' => '₮' ],
            ['iso3' =>'MUR' , 'name' => 'Mauritius Rupee', 'symbol' => '₨' ],
            ['iso3' =>'MXN' , 'name' => 'MXV Mexican Peso Mexican Unidad de Inversion (UDI]', 'symbol' => '$' ],
            ['iso3' =>'MYR' , 'name' => 'Malaysian Ringgit', 'symbol' => 'RM' ],
            ['iso3' =>'MZN' , 'name' => 'Metical', 'symbol' => 'MT' ],
            ['iso3' =>'NGN' , 'name' => 'Naira', 'symbol' => '₦' ],
            ['iso3' =>'NIO' , 'name' => 'Cordoba Oro', 'symbol' => 'C$' ],
            ['iso3' =>'NOK' , 'name' => 'Norwegian Krone', 'symbol' => 'kr' ],
            ['iso3' =>'NPR' , 'name' => 'Nepalese Rupee', 'symbol' => '₨' ],
            ['iso3' =>'NZD' , 'name' => 'New Zealand Dollar', 'symbol' => '$' ],
            ['iso3' =>'OMR' , 'name' => 'Rial Omani', 'symbol' => '﷼' ],
            ['iso3' =>'PAB' , 'name' => 'USD Balboa US Dollar', 'symbol' => 'B/.' ],
            ['iso3' =>'PEN' , 'name' => 'Nuevo Sol', 'symbol' => 'S/.' ],
            ['iso3' =>'PHP' , 'name' => 'Philippine Peso', 'symbol' => 'Php' ],
            ['iso3' =>'PKR' , 'name' => 'Pakistan Rupee', 'symbol' => '₨' ],
            ['iso3' =>'PLN' , 'name' => 'Zloty', 'symbol' => 'zł' ],
            ['iso3' =>'PYG' , 'name' => 'Guarani', 'symbol' => 'Gs' ],
            ['iso3' =>'QAR' , 'name' => 'Qatari Rial', 'symbol' => '﷼' ],
            ['iso3' =>'RON' , 'name' => 'New Leu', 'symbol' => 'lei' ],
            ['iso3' =>'RSD' , 'name' => 'Serbian Dinar', 'symbol' => 'Дин.' ],
            ['iso3' =>'RUB' , 'name' => 'Russian Ruble', 'symbol' => 'руб' ],
            ['iso3' =>'SAR' , 'name' => 'Saudi Riyal', 'symbol' => '﷼' ],
            ['iso3' =>'SBD' , 'name' => 'Solomon Islands Dollar', 'symbol' => '$' ],
            ['iso3' =>'SCR' , 'name' => 'Seychelles Rupee', 'symbol' => '₨' ],
            ['iso3' =>'SEK' , 'name' => 'Swedish Krona', 'symbol' => 'kr' ],
            ['iso3' =>'SGD' , 'name' => 'Singapore Dollar', 'symbol' => '$' ],
            ['iso3' =>'SHP' , 'name' => 'Saint Helena Pound', 'symbol' => '£' ],
            ['iso3' =>'SOS' , 'name' => 'Somali Shilling', 'symbol' => 'S' ],
            ['iso3' =>'SRD' , 'name' => 'Surinam Dollar', 'symbol' => '$' ],
            ['iso3' =>'SVC' , 'name' => 'USD El Salvador Colon US Dollar', 'symbol' => '$' ],
            ['iso3' =>'SYP' , 'name' => 'Syrian Pound', 'symbol' => '£' ],
            ['iso3' =>'THB' , 'name' => 'Baht', 'symbol' => '฿' ],
            ['iso3' =>'TRY' , 'name' => 'Turkish Lira', 'symbol' => 'TL' ],
            ['iso3' =>'TTD' , 'name' => 'Trinidad and Tobago Dollar', 'symbol' => 'TT$' ],
            ['iso3' =>'TWD' , 'name' => 'New Taiwan Dollar', 'symbol' => 'NT$' ],
            ['iso3' =>'UAH' , 'name' => 'Hryvnia', 'symbol' => '₴' ],
            ['iso3' =>'USD' , 'name' => 'US Dollar', 'symbol' => '$' ],
            ['iso3' =>'UYU' , 'name' => 'UYI Uruguay Peso en Unidades Indexadas', 'symbol' => '$U' ],
            ['iso3' =>'UZS' , 'name' => 'Uzbekistan Sum', 'symbol' => 'лв' ],
            ['iso3' =>'VEF' , 'name' => 'Bolivar Fuerte', 'symbol' => 'Bs' ],
            ['iso3' =>'VND' , 'name' => 'Dong', 'symbol' => '₫' ],
            ['iso3' =>'XCD' , 'name' => 'East Caribbean Dollar', 'symbol' => '$' ],
            ['iso3' =>'YER' , 'name' => 'Yemeni Rial', 'symbol' => '﷼' ],
            ['iso3' =>'ZAR' , 'name' => 'Rand', 'symbol' => 'R' ],
        ]);
    }
}
